---
- name: Copy code to the build directory (copy back assume code was changed)
  command: rsync -rv --delete \
             "{{ code_share_directory }}/mysql-{{ mysql_version }}/" \
             "{{ code_build_directory }}/mysql-{{ mysql_version }}/"

- name: Create cmake option
  set_fact:
    opt_str: "-D{{ item.key }}={{ item.value }}"
  register: result
  with_dict: cmake_options

# @see http://dev.mysql.com/doc/refman/5.6/en/source-installation.html
- name: cmake / make / make install
  command: "{{ item }}"
  args:
    chdir: "{{ code_build_directory }}/mysql-{{ mysql_version }}"
  with_items:
    - "cmake . {{ result.results | join(' ', attribute='ansible_facts.opt_str') }}"
    - 'make'
    - 'make install'
  notify: restart mysql server
