---
- name: Download mysql source code
  get_url:
    url: "{{ mysql_code_url }}"
    dest: /tmp/
  register: downloaded_tarball

- name: Ensure deploy directory existence
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ code_build_directory }}"
    - "{{ code_share_directory }}"

- name: Unarchive code
  unarchive:
    src: "{{ downloaded_tarball.dest }}"
    dest: "{{ code_build_directory }}/"
    copy: no

- name: Copy code to the share directory
  command: rsync -rv --delete \
             "{{ code_build_directory }}/mysql-{{ mysql_version }}" \
             "{{ code_share_directory }}/"
