---
# @see http://dev.mysql.com/doc/refman/5.6/en/source-installation.html
- name: Set directory privileges
  file:
    path: "{{ mysql_base_directory }}"
    state: directory
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    recurse: true

# http://dev.mysql.com/doc/refman/5.6/en/mysql-install-db.html
- name: Initialize MySQL data directory
  command: ./scripts/mysql_install_db --user="{{ mysql_user}}" --basedir="{{ mysql_base_directory }}" --datadir="{{ mysql_data_directory }}"
  args:
    chdir: "{{ mysql_base_directory }}"

- name: Change directory owners for mysql base/data directory
  file:
    path: "{{ item.value.path }}"
    state: directory
    owner: "{{ item.value.owner }}"
    group: "{{ mysql_group}}"
    recurse: true
  with_dict:
    base_dir:
      path: "{{ mysql_base_directory }}"
      owner: root
    data_dir:
      path: "{{ mysql_data_directory }}"
      owner: "{{ mysql_group }}"

- name: Setup init script
  command: cp "{{ mysql_base_directory }}/support-files/mysql.server" "/etc/init.d/mysql"

# I will replace this to the PATH settings
- name: Setup path for mysql commands
  file:
    src: "{{ mysql_base_directory }}/bin/mysql"
    dest: /usr/bin/mysql
    state: link

- name: Copy my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
