---
- include_vars: "{{ ansible_os_family|lower }}.yml"
  tags:
    - pkg_install

# TODO: this should be overwritten by include + with_items after ansible 2.0 release
- include: 'pkg_install.yml'
  tags: pkg_install

- include: 'setup_user.yml'
  tags: setup_user

- include: 'deploy_code.yml'
  tags: deploy_code

# restart is triggerred
- include: 'build.yml'
  tags: build

- include: 'test.yml'
  when: skip_tests != True
  tags: test

# restart is triggered
- include: 'install_db.yml'
  tags: install_db
