---
mysql_version: 5.5.41
mysql_code_url: http://downloads.mysql.com/archives/get/file/mysql-{{ mysql_version }}.tar.gz

# please add options for cmake
# @see http://dev.mysql.com/doc/refman/5.6/en/source-configuration-options.html
cmake_options:
  DEFAULT_CHARSET: utf-8
  DEFAULT_COLLATION: utf8_general_ci
  WITH_DEBUG: true

code_deploy_directory: /opt
mysql_data_directory: /var/lib/mysql
