---
mysql_version: 5.5.41
mysql_code_url: http://downloads.mysql.com/archives/get/file/mysql-{{ mysql_version }}.tar.gz

# please add options for cmake
# @see http://dev.mysql.com/doc/refman/5.6/en/source-configuration-options.html
cmake_options:
  DEFAULT_CHARSET: utf8
  DEFAULT_COLLATION: utf8_general_ci
  WITH_DEBUG: 'true'

# /vagrant is shared directory between host and guest
code_share_directory: /vagrant/src
code_build_directory: /opt/src

mysql_base_directory: /usr/local/mysql
mysql_data_directory: /var/lib/mysql/data

test_env:
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8

# please change this config to True if you want to skip tests
skip_tests: True
