---
# @see http://dev.mysql.com/doc/refman/5.6/en/source-installation.html
- name: cmake / make / make install
  command: "{{ item }}"
  args:
    chdir: "{{ code_deploy_directory }}/mysql-{{ mysql_version}}"
  with_items:
    - 'cmake .'
    - 'make'
    - 'make install'
